execute pathogen#infect()
syntax on
filetype plugin indent on

let g:gruvbox_italic=1
colorscheme gruvbox
set termguicolors
set background=dark

set number
set tabstop=4
set softtabstop=4
set expandtab
set cursorline
set showmatch

set incsearch
set hlsearch

inoremap jj <esc>
nnoremap <silent> <Esc> :nohlsearch<Bar>:echo<CR>
map <C-n> :NERDTreeToggle<CR>
